
# Promise

## Promise🤙
🙍‍♂️ 프로미스란 프로미스가 생성된 당시에 그 값을 필수적으로 알 필요가 없을 때 사용하는 **`proxy`** 이다. (좀 나중에 알아도 될 때!)

<br>

🙋‍♂️ 프로미스는 비동기 작업의 **`성공 결과`** 나 **`실패 이유`** 에 대해 **연관된 핸들러를 할당**할 수 있도록 한다.

<br>

🙆‍♂️ 프로미스는 세가지 상태에서 존재한다.
- **`pending`** : initial state, neither fulfilled nor rejected.
- **`fulfilled`** : meaning that the operation was completed successfully.
- **`rejected`** : meaning that the operation failed.

<br>

💁‍♂️ **Pending Promise**는 값을 만족시킬 수도 있고, **(fulfilled)** 어떤 이유에 의해 거절당할 수도 있다. **(rejected)**

<br>

🤷‍♂️ 두 개의 옵션 (fulfilled or rejected)중 하나가 발생하면, **`then`** 로 queued up 된 핸들러들이 call back 된다.

<br>

🙇‍♂️ Pending 상태에서 벗어난 promise가 핸들러가 붙어있다면, 그 상태에 알맞은 핸들러가 call back 되기 때문에  **asynchronous operation completing** 과 **its handlers being attached** 사이에 **`race condition`** 은 없다.

<br>

## then method👉

```js
const successCallback = function () { };
const errorCallback = function () { };

fetch('https://jsonplaceholder.typicode.com/users') // Promise-A
  .then(successCallback, errorCallback); // Promise-B
```

<br>


**1. fetch 함수의 작업이 ㅁㅁ 했을 때**
- **성공** : then method의 `successCallback`이 실행
- **실패** : then method의 `errorCallback`이 실행

<br>

**2. Promise-B 객체의 상태와 결과는 then 함수에 예약된 콜백함수에 따라 결정된다.**

<br>


### Promise 객체의 상태와 결과

<br>

**1. 실행된 콜백이 어떤 값을 리턴하는 경우**

- **Promise 객체를 리턴하는 경우**

```js
fetch('https://jsonplaceholder.typicode.com/users')
  .then((response) => response.json())// Promise Object Return
  .then((result) => { console.log(result) });
```

<br>

첫 번째 then method가 리턴하는 객체를 PromiseA 라 하고, response.json()이 리턴하는 객체를 PromiseB 라고 하자.


**🙍‍♂️ PromiseA 객체의 상태와 결과는 PromiseB 객체의 상태와 결과를 똑같이 갖는다.**

<br>

- **Promise 객체 이외의 값을 리턴하는 경우**

숫자형, 문자형, 일반 객체 등을 리턴하는 경우에 **🙍‍♂️ then method가 리턴했던 Promise 객체는 fulfilled 상태가 되고 작업 결과로 콜백함수의 리턴 값을 가진다.**


```js
// Internet Disconnected
fetch('https://jsonplaceholder.typicode.com/users')
  .then((response) => response.json(), (error) => 'Try again!')
  .then((result) => { console.log(result) });
```

<br>

지금 인터넷이 끊겼다고 가정해보자. <br>

fetch 함수의 request는 네트워크 오류로 인해서 rejected 되고, attached된 call back 함수의 두 번째 리턴값인 'Try again'이 then method의 프로미스 객체의 결과 값이 되고 상태는 fulfilled가 된다. <br>
*(rejected 되는건 fetch함수의 Promise객체!!!)*


<br>

**2. 실행된 콜백이 아무 값도 리턴하지 않는 경우**
```js
// Internet Disconnected
fetch('https://jsonplaceholder.typicode.com/users')
  .then((response) => response.json(), (error) => { alert('Try again!'); })
  .then((result) => { console.log(result) });
```

<br>

무언가를 리턴하지 않고 어떤 함수를 실행만 시키는 call back 함수가 등록되있다면 then 함수에 등록된 error 처리 call back은 어떤 값도 리턴하지 않는다. 
<br>

이런 경우 리턴 값이 없으므로 undefined값이 할당되므로, **🙍‍♂️ then method가 리턴한 프로미스 객체의 상태 값은 fulfilled가 되고 결과 값으로 undefined가 할당된다.**

<br>

**3. 실행된 콜백 내부에서 에러가 발생했을 때**

```js
fetch('https://jsonplaceholder.typicode.com/users')
  .then((response) => { 
        ...
        add(1, 2); // ReferenceError 발생
        ... 
  });

fetch('https://jsonplaceholder.typicode.com/users')
  .then((response) => { 
        ...
        throw new Error('failed'); 
        ... 
  });
```
<br>

call back 함수가 에러가 발생하면 **🙍‍♂️ then method가 리턴하는 Promise 객체는 rejected되고 결과 값으로 에러 객체 (실패 이유 - reason)을 가지게 된다.** 

<br>

이 Promise 객체의 내부를 살펴보면 PromiseState와 PromiseResult란 내부슬롯이 있는데 상태는 rejected고 값은 error object가 할당돼 있는 것을 알 수 있다. 

 <br>
 
**4. 아무런 콜백도 실행되지 않을 때**
```js
// Internet Disconnected
fetch('https://www.google.com') // Promise-1
  .then((response) => response.text()) // Promise-2
  .then((result) => { console.log(result) }, (error) => { alert(error) }); 
```

 <br>
 
인터넷이 끊겨서 fetch함수가 리턴한 Promise 객체가 rejected 되어서 다음 then method로 attach 한 두 번째 에러 처리 call back 함수로 핸들링을 해주어야 하는데 그게 없다..!

 <br>
 
이런 경우 아무런 call back도 실행되지 않는데 이때 이 then method가 리턴한 **🙍‍♂️ Promise 객체 (Promise - 2)는 Promise - 1 객체와 같은 상태와 결과 값**을 가지게 된다.
 
  <br>
 
## Promise Chain🔗

🙍‍♂️ catch 메소드는 then 메소드의 두 번째 call back 함수를 등록하는 것과 같은 결과를 보여주는 handler 함수이다.

🙋‍♂️ catch메소드는 Promise Chain의 가장 마지막에 부착해 모든 rejected 상황에 대처할 수 있도록 하는 것이 좋지만 중간에 쓰는 경우도 있다.

🙆‍♂️ 중간에 쓰는 경우는 catch메소드가 중간에 에러가 발생해도 그 대안을 뒤로 넘겨줄 수 있는 경우에 사용한다.

<br>

```js
fetch('https://friendbook.com/my/newsfeeds')
  .then((response) => response.json()) // -- A
  .then((result) => { // -- B
    const feeds = result;
    // 피드 데이터 가공...
    return processedFeeds; 
  })
  .catch((error) => { // -- C
    // 미리 저장해둔 일반 뉴스를 보여주기  
    const storedGeneralNews = getStoredGeneralNews();
    return storedGeneralNews;
  })
  .then((result) => { /* 화면에 표시 */ }) // -- D
  .catch((error) => { /* 에러 로깅 */ }); // -- E
```

<br>

만약 서버로부터 뉴스피드가 잘 조회되면 현재 코드에서 A, B, D 줄에 있는 콜백들이 잘 실행되고, 사용자에게 뉴스피드가 잘 표시된다.

<br>

하지만 만약 사용자의 컴퓨터가 인터넷에 연결되어 있지 않은 상태라서 fetch 함수의 작업이 실패한다면 Promise Chain의 작업은 실패했다고 생각하고, C줄에 있는 콜백을 보자.

<br>

fetch 함수의 작업이 실패하면 C 줄의 콜백이 실행된다. 

<br>

나중에 오프라인 상태가 될 때를 대비해서 모든 사람이 공통으로 볼 수 있는, 텍스트로만 이루어진 최근 일반 뉴스 데이터를 갱신해서 웹 브라우저에 저장한다고 하면 C줄의 콜백은 바로 이렇게 저장해둔 일반 뉴스 데이터를 그대로 가져오는 기능을 한다. 
